-- JBR Demo Products Seed Data
-- 80 products: 10 per category

-- Rackets (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Astrox 99 Pro', 'yonex-astrox-99-pro', 'Raket profesional dengan Rotational Generator System', 'Yonex', 'UNISEX', 2850000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1617083934555-ac7b4d0c8be5?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Nanoflare 800 Pro', 'yonex-nanoflare-800-pro', 'Raket speed dengan Sonic Flare System', 'Yonex', 'UNISEX', 2650000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Axforce 100', 'li-ning-axforce-100', 'Power raket dengan TB Nano', 'Li-Ning', 'UNISEX', 2200000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1617083934555-ac7b4d0c8be5?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Bladex 900', 'li-ning-bladex-900', 'Signature racket Viktor Axelsen', 'Li-Ning', 'MEN', 2750000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Thruster Ryuga II', 'victor-thruster-ryuga-ii', 'FREE-CORE technology', 'Victor', 'UNISEX', 2100000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1599577446220-b6542d8d2c92?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Auraspeed 100X', 'victor-auraspeed-100x', 'Raket ringan wanita', 'Victor', 'WOMEN', 1950000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1617083934555-ac7b4d0c8be5?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Voltric Z Force II', 'yonex-voltric-z-force-ii', 'Legendary power racket', 'Yonex', 'MEN', 1800000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Turbocharging 75C', 'li-ning-turbocharging-75c', 'All-around racket', 'Li-Ning', 'UNISEX', 1650000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1617083934555-ac7b4d0c8be5?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Jetspeed S12F', 'victor-jetspeed-s12f', 'Fast racket Aerodynamic', 'Victor', 'UNISEX', 1950000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Arcsaber 11 Pro', 'yonex-arcsaber-11-pro', 'Control oriented', 'Yonex', 'UNISEX', 2450000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1599577446220-b6542d8d2c92?w=800'] FROM categories WHERE slug='rackets' ON CONFLICT (slug) DO NOTHING;

-- Shoes (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Power Cushion 65 Z3', 'yonex-power-cushion-65-z3', 'Power Cushion shock absorption', 'Yonex', 'MEN', 1850000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Aerus Z2 Women', 'yonex-aerus-z2-women', 'Sepatu ringan wanita', 'Yonex', 'WOMEN', 1950000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Saga II Lite', 'li-ning-saga-ii-lite', 'Carbon fiber stability', 'Li-Ning', 'UNISEX', 1450000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor A970ACE', 'victor-a970ace', 'ENERGYMAX 3.0 cushioning', 'Victor', 'MEN', 1650000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Power Cushion 88', 'yonex-power-cushion-88', 'Dial-wire quick fit', 'Yonex', 'UNISEX', 2100000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Ranger TD', 'li-ning-ranger-td', 'Entry level shoes', 'Li-Ning', 'MEN', 1250000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor SH-A830II', 'victor-sh-a830ii', 'Womens badminton shoes', 'Victor', 'WOMEN', 1350000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Comfort Z3', 'yonex-comfort-z3', 'Comfort-focused design', 'Yonex', 'UNISEX', 1550000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning AYAR003 Pro', 'li-ning-ayar003-pro', 'BOUNSE+ technology', 'Li-Ning', 'MEN', 1750000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor P9200II', 'victor-p9200ii', 'REACTIVE-FOAM performance', 'Victor', 'UNISEX', 1450000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] FROM categories WHERE slug='shoes' ON CONFLICT (slug) DO NOTHING;

-- Bags (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Pro Racket Bag 9R', 'yonex-pro-racket-bag-9r', 'Tas raket 9 raket', 'Yonex', 'UNISEX', 950000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Backpack ABSS289', 'li-ning-backpack-abss289', 'Backpack 25L', 'Li-Ning', 'UNISEX', 650000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor BR9213 12R', 'victor-br9213-12r', 'Tas 12 raket', 'Victor', 'UNISEX', 1250000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Tournament Bag', 'yonex-tournament-bag', 'Tournament series', 'Yonex', 'UNISEX', 1100000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Rectangular Bag', 'li-ning-rectangular-bag', '3 compartments 9R', 'Li-Ning', 'UNISEX', 850000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor BR9712 Bag', 'victor-br9712-bag', 'Compact 6R', 'Victor', 'UNISEX', 750000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Pro Backpack', 'yonex-pro-backpack', 'Backpack 2 raket', 'Yonex', 'UNISEX', 550000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Duffel Bag', 'li-ning-duffel-bag', 'Duffel serbaguna', 'Li-Ning', 'UNISEX', 450000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Backpack BR9014', 'victor-backpack-br9014', 'Sporty backpack', 'Victor', 'UNISEX', 500000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Active Bag', 'yonex-active-bag', 'Entry level 3R', 'Yonex', 'UNISEX', 420000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'] FROM categories WHERE slug='bags' ON CONFLICT (slug) DO NOTHING;

-- Apparel (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Game Shirt Men', 'yonex-game-shirt-men', 'Very Cool Dry', 'Yonex', 'MEN', 450000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Competition Dress', 'li-ning-competition-dress', 'AT DRY dress wanita', 'Li-Ning', 'WOMEN', 550000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Game Shirt T-40002', 'victor-game-shirt-t-40002', 'ECO-DRY fabric', 'Victor', 'UNISEX', 350000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Game Short', 'yonex-game-short', 'Celana pendek', 'Yonex', 'MEN', 380000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Skort Women', 'li-ning-skort-women', 'Skirt + short', 'Li-Ning', 'WOMEN', 420000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Jacket J-20608', 'victor-jacket-j-20608', 'Jaket windbreaker', 'Victor', 'UNISEX', 650000, 'PRELOVED', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Polo Shirt', 'yonex-polo-shirt', 'Polo casual', 'Yonex', 'MEN', 320000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Training Pants', 'li-ning-training-pants', 'Celana training', 'Li-Ning', 'UNISEX', 480000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Tank Top Women', 'victor-tank-top-women', 'Tank top racerback', 'Victor', 'WOMEN', 280000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Track Suit', 'yonex-track-suit', 'Jacket + pants set', 'Yonex', 'UNISEX', 1250000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'] FROM categories WHERE slug='apparel' ON CONFLICT (slug) DO NOTHING;

-- Shuttlecocks (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Aerosensa 50', 'yonex-aerosensa-50', 'Tournament goose feather', 'Yonex', 'UNISEX', 450000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning A+90', 'li-ning-aplus90', 'Premium goose feather', 'Li-Ning', 'UNISEX', 380000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Champion Gold', 'victor-champion-gold', 'Premium tournament', 'Victor', 'UNISEX', 420000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Mavis 350', 'yonex-mavis-350', 'Nylon latihan', 'Yonex', 'UNISEX', 150000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning G500', 'li-ning-g500', 'Training feather', 'Li-Ning', 'UNISEX', 280000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor NS5000 Nylon', 'victor-ns5000-nylon', 'Nylon pemula', 'Victor', 'UNISEX', 120000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Aerosensa 30', 'yonex-aerosensa-30', 'Training club level', 'Yonex', 'UNISEX', 350000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning A+300', 'li-ning-aplus300', 'Club duck feather', 'Li-Ning', 'UNISEX', 320000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Gold 1', 'victor-gold-1', 'High-end competition', 'Victor', 'UNISEX', 390000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Mavis 2000', 'yonex-mavis-2000', 'Premium nylon cork', 'Yonex', 'UNISEX', 180000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1613916975836-d7e16adc1cb2?w=800'] FROM categories WHERE slug='shuttlecocks' ON CONFLICT (slug) DO NOTHING;

-- Grips (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Super Grap AC-102', 'yonex-super-grap-ac102', 'Tacky overgrip 3pc', 'Yonex', 'UNISEX', 85000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning GP1000', 'li-ning-gp1000', 'Soft feel overgrip', 'Li-Ning', 'UNISEX', 65000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor GR262 Towel', 'victor-gr262-towel', 'Towel grip absorbent', 'Victor', 'UNISEX', 95000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Nanogy AC-150', 'yonex-nanogy-ac150', 'Thin 0.6mm', 'Yonex', 'UNISEX', 75000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning GP2000', 'li-ning-gp2000', 'Cushion replacement', 'Li-Ning', 'UNISEX', 55000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor GR234 Wet', 'victor-gr234-wet', 'Wet overgrip tacky', 'Victor', 'UNISEX', 70000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Wave Grap AC-104', 'yonex-wave-grap-ac104', 'Wave anti-slip', 'Yonex', 'UNISEX', 90000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning GP1100 Pro', 'li-ning-gp1100-pro', 'Pro grade', 'Li-Ning', 'UNISEX', 80000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Fishbone GR251', 'victor-fishbone-gr251', 'Fishbone pattern', 'Victor', 'UNISEX', 85000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Clean Grap AC-146', 'yonex-clean-grap-ac146', 'Antibacterial', 'Yonex', 'UNISEX', 95000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='grips' ON CONFLICT (slug) DO NOTHING;

-- Strings (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex BG65', 'yonex-bg65', 'Best-selling durable', 'Yonex', 'UNISEX', 85000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning No.1', 'li-ning-no1', 'Premium repulsion', 'Li-Ning', 'UNISEX', 95000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor VBS-70', 'victor-vbs-70', 'All-round balanced', 'Victor', 'UNISEX', 80000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex BG80', 'yonex-bg80', 'High repulsion power', 'Yonex', 'UNISEX', 110000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning No.7', 'li-ning-no7', 'Durable training', 'Li-Ning', 'UNISEX', 75000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor VBS-66 Nano', 'victor-vbs-66-nano', 'Thin gauge control', 'Victor', 'UNISEX', 90000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Aerosonic', 'yonex-aerosonic', 'Thinnest 0.61mm', 'Yonex', 'UNISEX', 125000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning No.5', 'li-ning-no5', 'Popular balanced', 'Li-Ning', 'UNISEX', 85000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor VBS-68P Power', 'victor-vbs-68p-power', 'Power repulsion', 'Victor', 'UNISEX', 95000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex NBG99', 'yonex-nbg99', 'Nanogy 99 control', 'Yonex', 'UNISEX', 115000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'] FROM categories WHERE slug='strings' ON CONFLICT (slug) DO NOTHING;

-- Accessories (10)
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Wristband AC-489', 'yonex-wristband-ac489', 'Cotton wristband', 'Yonex', 'UNISEX', 65000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Headband SP131', 'victor-headband-sp131', 'Elastic headband', 'Victor', 'UNISEX', 75000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Racket Sack AC544', 'yonex-racket-sack-ac544', 'Single racket cover', 'Yonex', 'UNISEX', 125000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Ankle Support', 'li-ning-ankle-support', 'Ankle protector', 'Li-Ning', 'UNISEX', 180000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Sport Socks VS-890', 'victor-sport-socks-vs890', 'Cushion sole socks', 'Victor', 'UNISEX', 85000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Knee Support MPS-80', 'yonex-knee-support-mps80', 'Knee protector', 'Yonex', 'UNISEX', 220000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Sport Cap', 'li-ning-sport-cap', 'Sport cap UV', 'Li-Ning', 'UNISEX', 150000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-003', id, 'Victor Towel TW-163', 'victor-towel-tw163', 'Sport towel cotton', 'Victor', 'UNISEX', 120000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-001', id, 'Yonex Vibration Stopper', 'yonex-vibration-stopper', 'String dampener', 'Yonex', 'UNISEX', 45000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (seller_id, category_id, title, slug, description, brand, gender, price, condition, stock, status, images) SELECT 'seller-002', id, 'Li-Ning Water Bottle', 'li-ning-water-bottle', 'Sport bottle 750ml', 'Li-Ning', 'UNISEX', 95000, 'NEW', 1, 'PUBLISHED', ARRAY['https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800'] FROM categories WHERE slug='accessories' ON CONFLICT (slug) DO NOTHING;
